### ISSUE TITLE
SNS topic name is not propagated to both serverelss functions

### ISSUE THREAD

**Issue by mkwatson** [cube-js/cube.js#1014]
**Describe the bug**
If you change [the SNS topic name in the process function definition](https://github.com/cube-js/cube.js/blob/master/packages/cubejs-cli/templates.js#L110), the service breaks because the topic is [hard-coded in the other serverless function](https://github.com/cube-js/cube.js/blob/master/packages/cubejs-serverless-aws/index.js#L15)

The HTTP API function expects an SNS topic that doesn't exist.

**To Reproduce**
1. In `serverless.yml` change the sns topic name here:
```
  cubejsProcess:
    handler: cube.process
    timeout: 630
    events:
      - sns: "\${self:service.name}-\${self:provider.stage}-process"
```
2. `serverless deploy`
3. Try to run any query (that's not already cached in Redis)

**Expected behavior**
The two serverless functions should always use the same SNS topic name.

**Version:**
[e.g. 0.4.5]

**Additional context**
It should be as easy as adding an environment variable to the HTTP API function that's the topic name. Something like:

```yaml
custom:
  sns-topic: "\${self:service.name}-\${self:provider.stage}-process"

functions:
  cubejs:
    handler: cube.api
    timeout: 30
    environment:
      SNS_TOPIC: ${self:custom.sns-topic}
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /{proxy+}
          method: ANY
  cubejsProcess:
    handler: cube.process
    timeout: 630
    events:
      - sns: ${self:custom.sns-topic}
```

And then read from that env variable in the HTTP API function:

```javascript
const topicArn = process.env.SNS_TOPIC
```
