### ISSUE TITLE
Select field alias considered as hidden [Snowflake]

### ISSUE THREAD

**Issue by mhd-adam** [cube-js/cube.js#1800]
**Describe the bug**
I have a simple CubeJs app which connects to a warehouse on Snowflake. 

```
Cube:
cube(`publisher_cube`, {
    sql: `SELECT * FROM PUBLISHER_CUBE`,
    measures: {
        impressions: {
            sql: `IMPRESSIONS`,
            shown:true,
            type: `sum`,
        }
    }
});
```

When I try to select impressions from the FE Playground it shows this error:
You requested hidden member: 'PUBLISHER_CUBE__IMPRESSIONS'. Please make it visible using `shown: true`. Please note primaryKey fields are `shown: false` by default: https://cube.dev/docs/joins#setting-a-primary-key.

The query seems to reach Snowflake warehouse and get executed successfully.

**To Reproduce**
1. Set up cubejs
2. Connect to Snowflake warehouse
3. Add a simple cube schema with 1 metric
4. Try to query the selected metric

**Expected behavior**
The metric query results.

**Screenshots**
![image](https://user-images.githubusercontent.com/65082505/104912400-e069e400-5994-11eb-8750-4d4c28ec629e.png)

From postmane:
![image](https://user-images.githubusercontent.com/65082505/104912442-eeb80000-5994-11eb-87a1-0a9626b4603f.png)

**Version:**
0.25.18

**Additional context**
The query that arrived at Snowflake and worked successfully:
```
SELECT
      sum("publisher_cube".impressions) "publisher_cube__impressions"
    FROM
      PUBLISHER_CUBE AS "publisher_cube"  LIMIT 10000
```
``
The schema generator fires the query right, but shows this as a result:
![image](https://user-images.githubusercontent.com/65082505/104913823-dd6ff300-5996-11eb-8525-1737debe6d4f.png)

**Comment by mhd-adam** [comment]
I found out that the issue is related to case sensitivity. There are 2 scenarios:
1- If use the metrics name in lowercases `impressions`, snowflake returns the alias capitalized `PUBLISHER_CUBE__IMPRESSIONS`.
2- If I try to capitalize the metric name `IMPRESSIOMS', the alias somehow changes to lowercase, underscored form `p_u_b_l_i_s_h_e_r__c_u_b_e___i_m_p_r_e_s_s_i_o_n_s`

**Comment by mhd-adam** [comment]
Solved it by altering the user on Snowflake and setting the `quoted_identifiers_ignore_case` to `false` (it's default values is `false` but I had changed it in the past). Thus, Snowflake returns the columns names were as intended to.

**Comment by pjleiwa** [comment]
Hi, I've got the same issue as described here. The solution  set `quoted_identifiers_ignore_case` to `false` does not work for me.

Are there any other suggestions what can be the cause of this issue?

This my  Cube:
```
cubes:
  - name: activities
    sql: "select objectid from  activities"
    data_source: default

    joins: []
    
    dimensions:
      - name: id
        sql: objectid
        type: number
        primary_key: true
        shown: true

    measures:
      - name: count
        type: count
        shown: true

    pre_aggregations:
      # pre-aggregation definitions go here.
      # learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started
```
This is the error that I get:

![image](https://github.com/cube-js/cube/assets/40674005/2c92ec69-b47a-4e3b-a23e-6abae25ebcd8)

Running the generated query in Snowflake works fine.
