### ISSUE TITLE
Docker-compose with Cube.JS

### ISSUE THREAD

**Issue by bilelsgh** [cube-js/cube.js#2613]
**Docker-compose with Cube.js**

Hey !
After having developped a complete application with Cube.JS I try to deploy it thanks to this docker-compose. When I start it I can go on the Playground but when I want to generate a chart I have the error "the relation public.users does not exist" !
I don't have this problem when I run the backend in local. The schema Users.js is auto-generated by cubejs with the command ```cubejs generate -t users``` .

Hop you can help me, thanks.

**docker-compose.yml**
```yml
version : "3.1"
services:
        ecom_db:
                image: postgres
                ports:
                        - "5556:5556"
                environment: 
                        POSTGRES_USER: osboxes
                        POSTGRES_PASSWORD: osboxes.org
                        POSTGRES_DB: ecom
                volumes:
                        - ./backend/bdd/ecom-dump.sql:/docker-entrypoint-init.d/ecom-dump.sql
                networks:
                        - mynetwork 

        cubejs_backend:
                image: cubejs_backend
                depends_on: 
                        - ecom_db
                networks:
                        - mynetwork
                ports:
                        - "4000:4000"
                links:
                        - ecom_db
                environment:
                        - CUBEJS_DB_HOST=ecom_db
                        - CUBEJS_DB_NAME=ecom 
                        - CUBEJS_DB_USER=osboxes
                        - CUBEJS_DB_PASS=osboxes.org
        angular_frontend:
                image: angular_frontend_bis
                depends_on: 
                        - cubejs_backend
                networks:
                        - mynetwork
                ports:
                        - "4200:4200"
                links: 
                        - cubejs_backend

        
networks:      
        mynetwork:
```
