### ISSUE TITLE
When run in Docker, Cube.js emits unnecessary error messages

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube.js#2785]
**Is your feature request related to a problem? Please describe.**
When Cube.js is run in Docker with an empty folder mounted and configured via environment variables:
- it complains that the `cube.js` file and the `schema` folder are missing
- it emits a lot of refresh scheduler errors

The absence of the `schema` folder prevents Cube.js from showing anything when you navigate to `localhost:4000`. It just shows a spinner. When the (empty!) `schema` folder is present, Cube.js shows the "Schema" tab, as it should.

**Describe the solution you'd like**
- Cube.js silently creates an empty `cube.js` file and the `schema` folder and complains only if it's unable to
- Cube.js doesn't emit any refresh scheduler errors until there's actually anything to refresh (at least one cube defined with at least one pre-aggregation)

**Describe alternatives you've considered**
—

**Additional context**
Docker image id: `0d0f3b1adb82`.

```yml
version: '2.2'

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
    environment:
      - CUBEJS_DB_TYPE=postgres
      - CUBEJS_DB_HOST=demo-db.cube.dev
      - CUBEJS_DB_USER=cube
      - CUBEJS_DB_PASS=12345
      - CUBEJS_DB_NAME=ecom

      - CUBEJS_API_SECRET=SECRET
      - CUBEJS_DEV_MODE=true
    volumes:
      - .:/cube/conf
```

<img width="752" alt="Screenshot 2021-05-20 at 12 50 28" src="https://user-images.githubusercontent.com/3852894/118958409-11b9e700-b96a-11eb-8aa0-56e1c4dc0fe1.png">
