### ISSUE TITLE
non-root user for cubestore

### ISSUE THREAD

**Issue by loremaps** [cube-js/cube.js#3048]
**Is your feature request related to a problem? Please describe.**

Follow [non-root user best practice](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user) for the docker image of cubestore.

**Describe the solution you'd like**

Be able to deploy cubestore in Kubernetes using non-root user. e.g.
```yaml
   ...
    spec:
      containers:
        - name: cubestore
          image: cubejs/cubestore:latest
         ...
      securityContext:
        runAsUser: 1000
```

**Describe alternatives you've considered**

N/A

**Additional context**

Right now if I run cubestore as non-root I get the following error:

```
2021-07-01 14:06:47,261 INFO  [cubestore::metastore] 1> Creating metastore from scratch in /cube/.cubestore/data/metastore
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "Failed to create RocksDB directory: `Os { code: 13, kind: PermissionDenied, message: \"Permission denied\" }`." }', /build/cubestore/cubestore/src/metastore/mod.rs:1542:40
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a143517d44cac50b20cbd3a0b579addab40dd399/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/a143517d44cac50b20cbd3a0b579addab40dd399/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/a143517d44cac50b20cbd3a0b579addab40dd399/library/core/src/option.rs:1300:5
   3: cubestore::metastore::RocksMetaStore::new
   4: cubestore::metastore::RocksMetaStore::load_from_remote::{{closure}}
   5:  as core::future::future::Future>::poll
   6:  as core::future::future::Future>::poll
   7:  as core::future::future::Future>::poll
   8:  as core::future::future::Future>::poll
   9:  as core::future::future::Future>::poll
  10:  as core::future::future::Future>::poll
  11: cubestored::main::{{closure}}
  12: tokio::runtime::enter::Enter::block_on
  13: tokio::runtime::thread_pool::ThreadPool::block_on
  14: tokio::runtime::Runtime::block_on
  15: cubestored::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by loremaps** [comment]
In case someone lands here, this can be solved by using the `CUBESTORE_DATA_DIR` environmental variable. e.g.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cubestore
  template:
    metadata:
      labels:
        app: cubestore
    spec:
      containers:
        - name: cubestore
          image: cubejs/cubestore
          ports:
            - containerPort: 3030
          env:
            - name: CUBESTORE_DATA_DIR
              value: /cube-data
          volumeMounts:
            - mountPath: /cube-data
              name: cubestore-data
      securityContext:
        runAsUser: 1000
      volumes:
        - name: cubestore-data
          emptyDir: {}
```
Thanks again for the support 😄
