### ISSUE TITLE
cubestore(Type coercion error): Error during planning: 'Int64 = Boolean' can't be evaluated because there isn't a common type to coerce the types to

### ISSUE THREAD

**Issue by adnanrahic** [cube-js/cube.js#3154]
**Describe the bug**
Cubestore error is displayed when running pre-aggregation.

Cubestore stacktrace:
```
2021-07-26 11:41:49,008 ERROR [cubestore::http] <pid:1> Error processing HTTP command: Internal: Error during planning: 'Int64 = Boolean' can't be evaluated because there isn't a common type to coerce the types to
   0: <cubestore::CubeError as core::convert::From<datafusion::error::DataFusionError>>::from
   1: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   3: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: tokio::runtime::task::harness::poll_future
  10: tokio::runtime::task::harness::Harness<T,S>::poll
  11: std::thread::local::LocalKey<T>::with
  12: tokio::runtime::thread_pool::worker::Context::run_task
  13: tokio::runtime::thread_pool::worker::Context::run
  14: tokio::macros::scoped_tls::ScopedKey<T>::set
  15: tokio::runtime::thread_pool::worker::run
  16: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  17: std::panicking::try
  18: tokio::runtime::task::harness::Harness<T,S>::poll
  19: tokio::runtime::blocking::pool::Inner::run
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
  21: core::ops::function::FnOnce::call_once{{vtable.shim}}
  22: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a143517d44cac50b20cbd3a0b579addab40dd399/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a143517d44cac50b20cbd3a0b579addab40dd399/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a143517d44cac50b20cbd3a0b579addab40dd399/library/std/src/sys/unix/thread.rs:71:17
  23: start_thread
  24: clone
```

Cube-api stack trace:
```
Error: Internal: Error during planning: 'Int64 = Boolean' can't be evaluated because there isn't a common type to coerce the types to
  at WebSocket.<anonymous> (/cube/node_modules/@cubejs-backend/cubestore-driver/src/WebSocketConnection.ts:87:30)
  at WebSocket.emit (events.js:314:20)
  at Receiver.receiverOnMessage (/cube/node_modules/ws/lib/websocket.js:970:20)
  at Receiver.emit (events.js:314:20)
  at Receiver.dataMessage (/cube/node_modules/ws/lib/receiver.js:502:14)
  at Receiver.getData (/cube/node_modules/ws/lib/receiver.js:435:17)
  at Receiver.startLoop (/cube/node_modules/ws/lib/receiver.js:143:22)
  at Receiver._write (/cube/node_modules/ws/lib/receiver.js:78:10)
  at doWrite (_stream_writable.js:403:12)
  at writeOrBuffer (_stream_writable.js:387:5)
  at Receiver.Writable.write (_stream_writable.js:318:11)
  at Socket.socketOnData (/cube/node_modules/ws/lib/websocket.js:1045:35)
  at Socket.emit (events.js:314:20)
  at addChunk (_stream_readable.js:297:12)
  at readableAddChunk (_stream_readable.js:272:9)
  at Socket.Readable.push (_stream_readable.js:213:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**To Reproduce**

**1. Docker Compose config**

```
version: '2.2'

services:
  cubestore:
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_REMOTE_DIR=/cube/data
    volumes:
      - .cubestore:/cube/data
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_SCHEDULED_REFRESH_DEFAULT=true

      - CUBEJS_DB_TYPE=clickhouse
      - CUBEJS_DB_HOST=github.demo.trial.altinity.cloud
      - CUBEJS_DB_PORT=8443
      - CUBEJS_DB_NAME=default
      - CUBEJS_DB_USER=demo
      - CUBEJS_DB_PASS=demo
      - CUBEJS_DB_SSL=true
      - CUBEJS_DB_CLICKHOUSE_READONLY=true

      - CUBEJS_CUBESTORE_HOST=cubestore

      - CUBEJS_API_SECRET=secret
    depends_on:
      - cubestore
    links:
      - cubestore
    volumes:
      - .:/cube/conf
```

**2. Cube**

```
cube(`GithubEvents`, {
  sql: `SELECT * FROM default.github_events`,

  preAggregations: {
    countAllStarsPerActorLogin: {
      type: `rollup`,
      external: true,
      scheduledRefresh: true,
      refreshKey: {
        every: '1 minute',
      },
      measureReferences: [count],
      dimensionReferences: [actorLogin],
      segmentReferences: [watchEvents],
      indexes: {
        countAllStarsPerActorLogin: {
          columns: [actorLogin],
        },
      },
    },
  },

  joins: {

  },

  segments: {
    watchEvents: {
      sql: `${CUBE}.event_type = 'WatchEvent'`,
    },
  },

...
}
```

**3. Query API**

```
curl \
  -H "Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2MjcyODg5MDcsImV4cCI6MTY1ODgyNDkwNywiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.SCbi-7qx0P_Ej2JVTv0z-xheDHYCL3o7-LX9qMfHXCI" \
  -G \
  --data-urlencode 'query={"measures": ["GithubEvents.count"],"order": [["GithubEvents.count","desc"]],"dimensions": ["GithubEvents.actorLogin"],"limit": 10000,"segments": ["GithubEvents.watchEvents"]}' \
  http://localhost:4000/cubejs-api/v1/load
```

**4. API returns error**

```
{"error":"Error: Internal: Error during planning: 'Int64 = Boolean' can't be evaluated because there isn't a common type to coerce the types to"}
```

**5. Console shows errors as shown above**

**Expected behavior**
Pre-aggregation should be saved in Cubestore.

**Version:**
v0.28.5
