### ISSUE TITLE
Support arm64 Docker images

### ISSUE THREAD

**Issue by robd003** [cube-js/cube.js#4407]
I'd like to use Cube.js Docker images on my M1 Mac and also on AWS Graviton2 machines. Unfortunately it looks like only x86_64 images are available at the moment.

**Comment by robd003** [comment]
If you guys are using GitHub actions to build your Docker images this is an easy way to do it:

```
---
name: Docker image builder
on: [push]

jobs:
  multi-arch-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image
        run: |
          docker buildx build \
            --platform ${{ matrix.arch }} \
            --load \
            --file ./Dockerfile . \
            --tag cubejs/cube:latest
```
