### ISSUE TITLE
Error during create table

### ISSUE THREAD

**Issue by devops-cloudbit** [cube-js/cube.js#5175]
Hi,
I am running cube in proudction mode using this docker-compose stack:

`
version: '2.2'

services:
  cube_api:
    restart: always
    image: cubejs/cube:v0.30.56
    ports:
      - 4000:4000
    env_file: .env
    volumes:
      - .:/cube/conf
    depends_on:
      - cubestore_worker_1
      - cubestore_worker_2
      - cube_refresh_worker
      - redis

  cube_refresh_worker:
    restart: always
    image: cubejs/cube:v0.30.56
    env_file: .env
    volumes:
      - .:/cube/conf
      - .empty:/cube/conf/node_modules/@cubejs-backend/

  cubestore_router:
    restart: always
    image: cubejs/cubestore:v0.30.56
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
    volumes:
      - .cubestore/router:/cube/data

  cubestore_worker_1:
    restart: always
    image: cubejs/cubestore:v0.30.56
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:10001
      - CUBESTORE_WORKER_PORT=10001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore/worker_1:/cube/data
    depends_on:
      - cubestore_router

  cubestore_worker_2:
    restart: always
    image: cubejs/cubestore:v0.30.56
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_2:10002
      - CUBESTORE_WORKER_PORT=10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore/worker_2:/cube/data
    depends_on:
      - cubestore_router

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    logging:
      driver: none
`

When I run this query:
`
curl \
 -H "Authorization: xxxx" \
 -G \
 --data-urlencode 'query={
  "measures": [
    "Customer.rollingCount"
  ],
  "order": {
    "Customer.createdAt": "asc"
  },
  "timeDimensions": [
    {
      "dimension": "Customer.createdAt",
      "granularity": "day"
    }
  ]
}' \
 http://localhost:4000/cubejs-api/v1/load | json_pp
`

I get this error:
`
{
   "error" : "Error: Error during create table: CREATE TABLE dev_pre_aggregations.customer_total_by_day_ly0neva1_n3d1ocgt_1hgmbbv (`account__id` varchar(64), `customer__environment_id` varchar(64), `customer__created_at_day` timestamp, `customer__rolling_count` bigint) LOCATION ?: User: Create table failed: Internal: No such file or directory (os error 2)"
}
`

This is my customer schema:

`cube(`Customer`, {
    sql: `SELECT * FROM public.customer`,
    
    preAggregations: {
      totalByDay: {
        measures: [
          Customer.rollingCount
        ],
        dimensions: [
          Account.id,
          Customer.environmentId,
        ],
        timeDimension: Customer.createdAt,
        granularity: `day`,
        refreshKey: {
          every: `1 minute`,
        },
      },
    },
    
    joins: {
      Account: {
        sql: `${CUBE}.account_id = ${Account}.id`,
        relationship: `belongsTo`
      },
      
      Environment: {
        sql: `${CUBE}.environment_id = ${Environment}.id`,
        relationship: `belongsTo`
      },
  
      Subscription: {
        sql: `${CUBE}.id = ${Subscription}.customer_id`,
        relationship: `hasMany`
      },
    },
    
    measures: {
      count: {
        type: `count`,
        drillMembers: [id, accountId, environmentId, billingId, crmId, defaultPaymentMethodId, crmHubspotContactId, crmHubspotCompanyId, name, refId, createdAt, updatedAt]
      },
  
      rollingCount: {
        sql: `id`,
        type: `count`,
        rollingWindow: {
          trailing: `unbounded`,
        },
      },
    },
    
    dimensions: {
      id: {
        sql: `id`,
        type: `string`,
        primaryKey: true
      },
      
      accountId: {
        sql: `account_id`,
        type: `string`
      },
      
      environmentId: {
        sql: `environment_id`,
        type: `string`
      },
      
      additionalMetaData: {
        sql: `additional_meta_data`,
        type: `string`
      },
      
      billingId: {
        sql: `billing_id`,
        type: `string`
      },
      
      billingLinkUrl: {
        sql: `billing_link_url`,
        type: `string`
      },
      
      crmId: {
        sql: `crm_id`,
        type: `string`
      },
      
      timezone: {
        sql: `timezone`,
        type: `string`
      },
      
      language: {
        sql: `language`,
        type: `string`
      },
      
      defaultPaymentMethodId: {
        sql: `default_payment_method_id`,
        type: `string`
      },
      
      crmHubspotContactId: {
        sql: `crm_hubspot_contact_id`,
        type: `string`
      },
      
      crmHubspotContactUrl: {
        sql: `crm_hubspot_contact_url`,
        type: `string`
      },
      
      crmHubspotCompanyId: {
        sql: `crm_hubspot_company_id`,
        type: `string`
      },
      
      crmHubspotCompanyUrl: {
        sql: `crm_hubspot_company_url`,
        type: `string`
      },
      
      email: {
        sql: `email`,
        type: `string`
      },
      
      name: {
        sql: `name`,
        type: `string`
      },
      
      user: {
        sql: `user`,
        type: `string`
      },
      
      refId: {
        sql: `ref_id`,
        type: `string`
      },
      
      createdAt: {
        sql: `created_at`,
        type: `time`
      },
      
      updatedAt: {
        sql: `updated_at`,
        type: `time`
      },
      
      billingSyncedAt: {
        sql: `billing_synced_at`,
        type: `time`
      },
      
      crmSyncedAt: {
        sql: `crm_synced_at`,
        type: `time`
      }
    },
    
    dataSource: `default`
  });`

I tried mounting cube/data dir to an s3 bucket in order to create a remote file system (as suggested here https://github.com/cube-js/cube.js/issues/3510) but it didn't help.

Help anyone?
I can't find anything that my lead to a solution

Thank you!

**Comment by paveltiunov** [comment]
@devops-cloudbit Your docker-compose configuration is incorrect. `CUBESTORE_REMOTE_DIR ` should point to the same physically accessible path from the router and worker nodes. But it isn't designed for production usage unless you're hosting the whole cluster on one machine. Please see https://cube.dev/docs/caching/running-in-production#storage.

**Comment by devops-cloudbit** [comment]
Hi @paveltiunov thank you for your response.
I changed my docker compose configuration to this one:

```
version: '2.2'
services:
  cubestore_router:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_WORKERS=cubestore_worker_1:9001,cubestore_worker_2:9001
      - CUBESTORE_REMOTE_DIR=/cube/data
    volumes:
      - .cubestore:/cube/data
  cubestore_worker_1:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:9001
      - CUBESTORE_WORKER_PORT=9001
      - CUBESTORE_META_ADDR=cubestore_router:9999
      - CUBESTORE_WORKERS=cubestore_worker_1:9001,cubestore_worker_2:9001
      - CUBESTORE_REMOTE_DIR=/cube/data
    depends_on:
      - cubestore_router
    volumes:
      - .cubestore:/cube/data
  cubestore_worker_2:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_SERVER_NAME=cubestore_worker_2:9001
      - CUBESTORE_WORKER_PORT=9001
      - CUBESTORE_META_ADDR=cubestore_router:9999
      - CUBESTORE_WORKERS=cubestore_worker_1:9001,cubestore_worker_2:9001
      - CUBESTORE_REMOTE_DIR=/cube/data
    depends_on:
      - cubestore_router
    volumes:
      - .cubestore:/cube/data
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
    environment:
      - CUBEJS_CUBESTORE_HOST=cubestore_router
    depends_on:
      - cubestore_router
    volumes:
      - .:/cube/conf
```

as suggested in the running-in-proudction article.

Why do we need remote dir and s3 bucket?
The remote dir is on the local machine? it shouldn't be mounted to an s3 bucket?

thanks

**Comment by devops-cloudbit** [comment]
Hi @paveltiunov 
this is my up-to-date docker compose stack:

```
version: '2.2'
services:
  cubestore_router:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_WORKERS=cubestore_worker_1:9001,cubestore_worker_2:9001
 #   - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_S3_BUCKET=xxxx
      - CUBESTORE_S3_REGION=us-east-2
      - CUBESTORE_AWS_ACCESS_KEY_ID=xxxx
      - CUBESTORE_AWS_SECRET_ACCESS_KEY=xxxx
    volumes:
      - .cubestore:/cube/data
  cubestore_worker_1:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:9001
      - CUBESTORE_WORKER_PORT=9001
      - CUBESTORE_META_ADDR=cubestore_router:9999
      - CUBESTORE_WORKERS=cubestore_worker_1:9001,cubestore_worker_2:9001
#     - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_S3_BUCKET=xxx
      - CUBESTORE_S3_REGION=us-east-2
      - CUBESTORE_AWS_ACCESS_KEY_ID=xxxx
      - CUBESTORE_AWS_SECRET_ACCESS_KEY=xxxx
    depends_on:
      - cubestore_router
    volumes:
      - .cubestore:/cube/data
  cubestore_worker_2:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_SERVER_NAME=cubestore_worker_2:9001
      - CUBESTORE_WORKER_PORT=9001
      - CUBESTORE_META_ADDR=cubestore_router:9999
      - CUBESTORE_WORKERS=cubestore_worker_1:9001,cubestore_worker_2:9001
#      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_S3_BUCKET=xxxx
      - CUBESTORE_S3_REGION=us-east-2
      - CUBESTORE_AWS_ACCESS_KEY_ID=xxxx
      - CUBESTORE_AWS_SECRET_ACCESS_KEY=xxxx
    depends_on:
      - cubestore_router
    volumes:
      - .cubestore:/cube/data
  cube:
    image: cubejs/cube:latest
    ports:
      - ${EXPOSED_PORT:-4000}:4000
    environment:
      - CUBEJS_CUBESTORE_HOST=cubestore_router
    depends_on:
      - cubestore_router
    volumes:
      - .:/cube/conf
```

but I still get this error in my website when trying to fetch data from cube:

`Access to XMLHttpRequest at 'https://xxxx/cubejs-api/v1/load?query=%7B%22measures%22%3A%5B%22Customer.rollingCount%22%5D%2C%22timeDimensions%22%3A%5B%7B%22dimension%22%3A%22Customer.createdAt%22%2C%22dateRange%22%3A%5B%222022-08-22%22%2C%222022-08-29%22%5D%2C%22granularity%22%3A%22day%22%7D%5D%2C%22order%22%3A%5B%5B%22Customer.createdAt%22%2C%22asc%22%5D%5D%2C%22filters%22%3A%5B%7B%22member%22%3A%22Customer.environmentId%22%2C%22operator%22%3A%22equals%22%2C%22values%22%3A%5B%2262224767-1395-4bbc-9158-a07591712f25%22%5D%7D%5D%7D&queryType=multi' from origin 'https://app-staging.stigg.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

and this error:
 ` GET https://xxxx/cubejs-api/v1/load?query=%7B%22measures%22%3A%5B%22Customer.rollingCount%22%5D%2C%22timeDimensions%22%3A%5B%7B%22dimension%22%3A%22Customer.createdAt%22%2C%22compareDateRange%22%3A%5B%5B%222022-08-22%22%2C%222022-08-29%22%5D%2C%5B%222022-08-15%22%2C%222022-08-22%22%5D%5D%7D%5D%2C%22filters%22%3A%5B%7B%22member%22%3A%22Customer.environmentId%22%2C%22operator%22%3A%22equals%22%2C%22values%22%3A%5B%2262224767-1395-4bbc-9158-a07591712f25%22%5D%7D%5D%7D&queryType=multi net::ERR_FAILED 502`

What am I doing wrong?
When I work in dev mode I don't get this error...
I get this error only when I work in production mode.

Also, when I tried to add this to my cube.js config file:
` http: {
    cors: {
      origin: '*',
      methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
      preflightContinue: false,
      optionsSuccessStatus: 204,
      maxAge: 86400,
      credentials: true,
    },
  },`

The cube app didn't load (I didn't see any errors in logs)
I just got 502 bad gateway on the browser.

Help please!
and thank you so much for your time :)
