### ISSUE TITLE
Error in production mode

### ISSUE THREAD

**Issue by devops-cloudbit** [cube-js/cube.js#5203]
Hi,
when I am in DEV_MODE = true, I have no problem querying the cube.
However, when I am in proudction mode, when I try to reach the cube I get '502 bad gateway' error.

this is my docker compose stack:
```

version: '2.2'
services:
  cubestore_router:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_WORKERS=cubestore_worker_1:9001,cubestore_worker_2:9001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_S3_BUCKET=xxxx
      - CUBESTORE_S3_REGION=us-east-2
      - CUBESTORE_AWS_ACCESS_KEY_ID=xxxx
      - CUBESTORE_AWS_SECRET_ACCESS_KEY=xxxx
    volumes:
      - .cubestore:/cube/data
  cubestore_worker_1:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:9001
      - CUBESTORE_WORKER_PORT=9001
      - CUBESTORE_META_ADDR=cubestore_router:9999
      - CUBESTORE_WORKERS=cubestore_worker_1:9001,cubestore_worker_2:9001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_S3_BUCKET=xxx
      - CUBESTORE_S3_REGION=us-east-2
      - CUBESTORE_AWS_ACCESS_KEY_ID=xxxx
      - CUBESTORE_AWS_SECRET_ACCESS_KEY=xxxx
    depends_on:
      - cubestore_router
    volumes:
      - .cubestore:/cube/data
  cubestore_worker_2:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_SERVER_NAME=cubestore_worker_2:9001
      - CUBESTORE_WORKER_PORT=9001
      - CUBESTORE_META_ADDR=cubestore_router:9999
      - CUBESTORE_WORKERS=cubestore_worker_1:9001,cubestore_worker_2:9001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_S3_BUCKET=xxxx
      - CUBESTORE_S3_REGION=us-east-2
      - CUBESTORE_AWS_ACCESS_KEY_ID=xxxx
      - CUBESTORE_AWS_SECRET_ACCESS_KEY=xxxx
    depends_on:
      - cubestore_router
    volumes:
      - .cubestore:/cube/data
  cube:
    image: cubejs/cube:latest
    ports:
      - ${EXPOSED_PORT:-4000}:4000
    environment:
      - CUBEJS_CUBESTORE_HOST=cubestore_router
    depends_on:
      - cubestore_router
    volumes:
      - .:/cube/conf
```

but I still get this error in my website when trying to fetch data from cube:

`Access to XMLHttpRequest at 'https://xxxx/cubejs-api/v1/load?query=%7B%22measures%22%3A%5B%22Customer.rollingCount%22%5D%2C%22timeDimensions%22%3A%5B%7B%22dimension%22%3A%22Customer.createdAt%22%2C%22dateRange%22%3A%5B%222022-08-22%22%2C%222022-08-29%22%5D%2C%22granularity%22%3A%22day%22%7D%5D%2C%22order%22%3A%5B%5B%22Customer.createdAt%22%2C%22asc%22%5D%5D%2C%22filters%22%3A%5B%7B%22member%22%3A%22Customer.environmentId%22%2C%22operator%22%3A%22equals%22%2C%22values%22%3A%5B%2262224767-1395-4bbc-9158-a07591712f25%22%5D%7D%5D%7D&queryType=multi' from origin 'https://xxxx' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

and this error:
`GET https://xxxx/cubejs-api/v1/load?query=%7B%22measures%22%3A%5B%22Customer.rollingCount%22%5D%2C%22timeDimensions%22%3A%5B%7B%22dimension%22%3A%22Customer.createdAt%22%2C%22compareDateRange%22%3A%5B%5B%222022-08-22%22%2C%222022-08-29%22%5D%2C%5B%222022-08-15%22%2C%222022-08-22%22%5D%5D%7D%5D%2C%22filters%22%3A%5B%7B%22member%22%3A%22Customer.environmentId%22%2C%22operator%22%3A%22equals%22%2C%22values%22%3A%5B%2262224767-1395-4bbc-9158-a07591712f25%22%5D%7D%5D%7D&queryType=multi net::ERR_FAILED 502`

What am I doing wrong?
When I work in dev mode I don't get this error...
I get this error only when I work in production mode.

Also, when I tried to add this to my cube.js config file:
`http: { cors: { origin: '*', methods: 'GET,HEAD,PUT,PATCH,POST,DELETE', preflightContinue: false, optionsSuccessStatus: 204, maxAge: 86400, credentials: true, }, },`

if I put a chrome extension that bypass the cors I get this error:
`subscriptions:1 Access to XMLHttpRequest at 'https://xxxx/cubejs-api/v1/load?query=%7B%22measures%22%3A%5B%22Subscription.rollingActiveCount%22%5D%2C%22timeDimensions%22%3A%5B%7B%22dimension%22%3A%22Subscription.createdAt%22%2C%22dateRange%22%3A%5B%222022-08-22%22%2C%222022-08-29%22%5D%2C%22granularity%22%3A%22day%22%7D%5D%2C%22order%22%3A%5B%5B%22Subscription.createdAt%22%2C%22asc%22%5D%5D%2C%22filters%22%3A%5B%7B%22member%22%3A%22Subscription.environmentId%22%2C%22operator%22%3A%22equals%22%2C%22values%22%3A%5B%2262224767-1395-4bbc-9158-a07591712f25%22%5D%7D%5D%7D&queryType=multi' from origin 'https://xxxx' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

The cube app didn't load (I didn't see any errors in logs)
I just got 502 bad gateway on the browser.

Help please!
and thank you so much for your time :)
