### ISSUE TITLE
Corrupted message received by cubestore-router

### ISSUE THREAD

**Issue by exister** [cube-js/cube.js#5532]
**Describe the bug**
I've followed docs and deployed cubejs and cubestore to k8s cluster.
During readinessProbe stage Api-server and refresh worker perform connection checks, which cause "Corrupted message" error in cubestore-router.

api-server logs
```
{"message":"Internal Server Error on liveness probe","driverType":"external","error":"Error: read ECONNRESET\n at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"}  

{"message":"Connection test completed successfully","driverType":"internal","dataSource":"default"}
```

refresh-worker logs
```
{"message":"Error querying db","error":"Error: read ECONNRESET\n at QueryQueue.parseResult (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:146:13)\n at QueryQueue.executeInQueue (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:57:19)\n at processTicksAndRejections (internal/process/task_queues.js:95:5)\n at async Promise.all (index 0)\n at OrchestratorApi.executeQuery (/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:85:20)\n at /cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:356:9\n at async Promise.all (index 0)\n at /cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:341:7\n at async Promise.all (index 3)\n at RefreshScheduler.refreshCubesRefreshKey (/cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:334:5)\n at async Promise.all (index 0)\n at RefreshScheduler.runScheduledRefresh (/cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:282:9)\n at async Promise.all (index 0)\n at Timeout._onTimeout (/cube/node_modules/@cubejs-backend/shared/src/promises.ts:139:9)","requestId":"scheduler-ca03670a-157b-446d-8ac2-5d4e1f12fc6c"}  

{"message":"Refresh Scheduler Error","error":"Error: read ECONNRESET","securityContext":{},"requestId":"scheduler-ca03670a-157b-446d-8ac2-5d4e1f12fc6c"}
```

cubestore-router logs
```
2022-10-27 17:30:47,536 ERROR [cubestore::cluster] <pid:1> Network error: Corrupted message received. Please check your worker and meta connection environment variables.
```

api-server env
```
- name: CUBEJS_CUBESTORE_HOST
  value: "cubestore-router"
- name: CUBEJS_CUBESTORE_PORT
  value: "9999"
```

refresh-worker env
```
- name: CUBEJS_CUBESTORE_HOST
  value: "cubestore-router"
- name: CUBEJS_CUBESTORE_PORT
  value: "9999"
- name: CUBEJS_REFRESH_WORKER
  value: "true"
```

cubestore-router env
```
- name: CUBESTORE_PORT
  value: "3306"
- name: CUBESTORE_HTTP_PORT
  value: "3030"
- name: CUBESTORE_META_PORT
  value: "9999"
- name: CUBESTORE_STATUS_PORT
  value: "3031"
- name: CUBESTORE_SERVER_NAME
  value: cubestore-router:9999
- name: CUBESTORE_WORKERS
  value: cubestore-workers-0.cubestore-workers:10000
```

cubestore-workers env
```
- name: POD_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
- name: CUBESTORE_META_ADDR
  value: cubestore-router:9999
- name: CUBESTORE_SERVER_NAME
  value: "$(POD_NAME).cubestore-workers:10000"
- name: CUBESTORE_WORKERS
  value: cubestore-workers-0.cubestore-workers:10000
- name: CUBESTORE_WORKER_PORT
  value: "10000"
```

**Version:**
v0.31.5
