### ISSUE TITLE
Multiple Datasources not working

### ISSUE THREAD

**Issue by jsbrain** [cube-js/cube.js#5999]
**Describe the bug**
Either the documentation is outdated or the environment variables simply don't work.

**To Reproduce**
Run

```yml
version: '3.8'

services:
  cube_api:
    restart: always
    image: cubejs/cube:v${CUBE_VERSION}
    container_name: cube-api
    ports:
      - 4000:4000
    environment:
      CUBEJS_DEV_MODE: true

      # Ref: https://cube.dev/docs/config/multiple-data-sources#configuring-data-sources-with-environment-variables
      CUBEJS_DATASOURCES: first,second

      CUBEJS_DS_first_DB_TYPE: ${first_DB_TYPE}
      CUBEJS_DS_first_DB_NAME: ${first_DB_NAME}
      CUBEJS_DS_first_DB_USER: ${first_DB_USER}
      CUBEJS_DS_first_DB_HOST: ${first_DB_HOST}
      CUBEJS_DS_first_DB_PORT: ${first_DB_PORT}

      CUBEJS_DS_second_DB_TYPE: ${second_DB_TYPE}
      CUBEJS_DS_second_DB_NAME: ${second_DB_NAME}
      CUBEJS_DS_second_DB_USER: ${second_DB_USER}
      CUBEJS_DS_second_DB_HOST: ${second_DB_HOST}
      CUBEJS_DS_second_DB_PORT: ${second_DB_PORT}

      CUBEJS_API_SECRET: ${CUBEJS_API_SECRET}
      CUBEJS_EXTERNAL_DEFAULT: true
      CUBEJS_SCHEDULED_REFRESH_DEFAULT: true
      CUBEJS_WEB_SOCKETS: true
    volumes:
      - .:/cube/conf
```

-> starting and trying to open playground results in:

```txt
Attaching to cube-api
cube-api  | Warning. There is no cube.js file. Continue with environment variables
cube-api  | 🔥 Cube Store (0.31.39) is assigned to 3030 port.
cube-api  | 🔓 Authentication checks are disabled in developer mode. Please use NODE_ENV=production to enable it.
cube-api  | 🦅 Dev environment available at http://localhost:4000
cube-api  | 🚀 Cube API server (0.31.39) is listening on 4000
cube-api  | 2023-01-12 14:35:23,921 INFO  [cubestored] <pid:18> Cube Store version 0.31.38
cube-api  | 2023-01-12 14:35:23,925 INFO  [cubestore::http::status] <pid:18> Serving status probes at 0.0.0.0:3031
cube-api  | 2023-01-12 14:35:23,927 INFO  [cubestore::metastore::rocks_fs] <pid:18> Using existing metastore in /cube/conf/.cubestore/data/metastore
cube-api  | 2023-01-12 14:35:23,977 INFO  [cubestore::http] <pid:18> Http Server is listening on 0.0.0.0:3030
cube-api  | 2023-01-12 14:35:23,977 INFO  [cubestore::mysql] <pid:18> MySQL port open on 0.0.0.0:13306
cube-api  | Internal Server Error: 8d0a1e16-b1bf-48c8-b612-0286574b301f-span-1 (460ms)
cube-api  | {
cube-api  |   "securityContext": {
cube-api  |     "iat": 1673534123,
cube-api  |     "exp": 1673620523
cube-api  |   }
cube-api  | } 
cube-api  | Error: Unsupported db type: undefined
cube-api  |     at Object.driverDependencies (/cube/node_modules/@cubejs-backend/server-core/src/core/DriverResolvers.ts:24:9)
cube-api  |     at Object.lookupDriverClass (/cube/node_modules/@cubejs-backend/server-core/src/core/DriverResolvers.ts:36:5)
cube-api  |     at Object.dialectFactory (/cube/node_modules/@cubejs-backend/server-core/src/core/OptsHandler.ts:450:9)
cube-api  |     at CompilerApi.dialectClass (/cube/node_modules/@cubejs-backend/server-core/src/core/server.ts:461:26)
cube-api  |     at CompilerApi.getDialectClass (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:91:38)
cube-api  |     at /cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:77:37
cube-api  |     at async Promise.all (index 0)
cube-api  |     at CompilerApi.createQueryFactory (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:73:7)
cube-api  |     at CompilerApi.getCompilers (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:63:27)
cube-api  |     at CompilerApi.metaConfig (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:188:13)
cube-api  |     at ApiGateway.meta (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:436:26)
cube-api  |     at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:247:9
```

**Version:**
docker tag: 0.31.39
