### ISSUE TITLE
Bigquery measure quoting issue in tesseract

### ISSUE THREAD

**Issue by AdeelK93** [cube-js/cube.js#9646]
**Describe the bug**
Really enjoyed working with cube so far! Very powerful tool!
Found a bug, which is quite easy to reproduce: when filtering a measure in bigquery, you get an error.
What's happening behind the scenes looks like `having count(*) = "1"` (note the quotes)

**To Reproduce**
1. Set up a table, any table in bigquery.
2. Set up any measure. I will use a very simple count measure, which cube auto-generates, but it's an error for all measures.
3. Add a measure filter for count

**Expected behavior**
I'd like a `having` clause with correctly typed query parameters

**Screenshots**
<img width="1413" alt="Image" src="https://github.com/user-attachments/assets/7a61fb1f-e924-4a26-b994-246ed678d0bc" />

**Minimally reproducible Cube Schema**
In case your bug report is data modelling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

```yaml
cubes:
  - name: test
    sql: select 1 as test_value
    data_source: default

    measures:
      - name: count
        type: count
```

```json
{
  "measures": [
    "test.count"
  ],
  "filters": [
    {
      "member": "test.count",
      "operator": "equals",
      "values": [
        "1"
      ]
    }
  ]
}
```

**Version:**
v1.3.19

**Additional context**
